apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-deployment
spec:
  selector:
    matchLabels:
      run: web
  replicas: 3
  template:
    metadata:
      labels:
        run: web
    spec:
      containers:
      - name: web
        image: luisf0425/go-service
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: go-service
  labels:
    run: web
spec:
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    run: web